/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTextPane;

public class Montagem extends javax.swing.JFrame {

        No raiz;
        
    
    public void addno(int chave, String nome){
        
        No novoNo = new No(chave, nome);
        
        if(raiz == null){
            raiz = novoNo;
        }else{
            No noUsado = raiz;
            
            No parente;
            
            while(true){
                parente = noUsado;
                
                if(chave < noUsado.chave){
                    noUsado = noUsado.filhoEsquerda;
                    
                    if(noUsado == null){
                        parente.filhoEsquerda = novoNo;
                        return;
                    }
                }else{
                    
                    noUsado = noUsado.filhoDireita;
                    
                    if(noUsado == null){
                        parente.filhoDireita = novoNo;
                        return;
                    }
                }
            }
        }
        
    }
    
        
    public void EmOrdem(No noUsado){ //esquerda  raiz   direita
        if(noUsado != null){
            
            if(noUsado.filhoEsquerda != null){
                EmOrdem(noUsado.filhoEsquerda);
            }
            
            System.out.println(noUsado);
            
               EmOrdem(noUsado.filhoDireita);
            
        }
    }
    
    public void preOrdem(No noUsado){  //Começa pela raiz
        if(noUsado != null){
            
            System.out.println(noUsado);
          
            preOrdem(noUsado.filhoEsquerda);
            
            preOrdem(noUsado.filhoDireita);
        }
    }
    
        public void postOrdem(No noUsado){  //Le da esquerda pra direita
        if(noUsado != null){
                      
            postOrdem(noUsado.filhoEsquerda);
            
            postOrdem(noUsado.filhoDireita);
            
            System.out.println(noUsado);

        }
    }
        
           public No encontrarNo(int chave){
   
       No noUsado = raiz;
       
       while(noUsado.chave != chave){
           
           if(chave < noUsado.chave ){
               
               noUsado = noUsado.filhoEsquerda;
           }else{
               noUsado = noUsado.filhoDireita;
           }
           
           if(noUsado == null){
               return null;
           }
         
       }
               return noUsado;

   }
       
           

    
    
    /**
     * Creates new form Montagem
     */
    public Montagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(255, 69, 105));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(111, 191, 115));
        jButton2.setText("Pre Ordem");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(111, 191, 115));
        jButton3.setText("Pos Ordem");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(111, 191, 115));
        jButton4.setText("Em Ordem");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           new main().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int num0 =  1; //rand.nextInt(100);
        int num1 = 2; //rand.nextInt(100);
        int num2 = 4; // rand.nextInt(100);
        int num3 = 8; //rand.nextInt(100);
        int num4 = 16; //rand.nextInt(100);
        int num5 = 32; // rand.nextInt(100);
        int num6 = 64; //rand.nextInt(100);
        int num7 = 128; //rand.nextInt(100);
        int num8 = 256; //rand.nextInt(100);
        int num9 = 512; //rand.nextInt(100);
        int num10 = 1024; // rand.nextInt(100);
       
        Montagem arvore = new Montagem();
        
        arvore.addno(num0, "");
        arvore.addno(num1, "");
        arvore.addno(num2, "");
        arvore.addno(num3, "");
        arvore.addno(num4, "");
        arvore.addno(num5, "");
        arvore.addno(num6, "");
        arvore.addno(num7, "");
        arvore.addno(num8, "");
        arvore.addno(num9, "");
        arvore.addno(num10, "");
        
        System.out.println("---------Pre Ordem---------");
         arvore.preOrdem(arvore.raiz);
         System.out.println("**********RAIZ**********: ");
         System.out.println("A raiz é: " + num0);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int num0 =  1; //rand.nextInt(100);
        int num1 = 2; //rand.nextInt(100);
        int num2 = 4; // rand.nextInt(100);
        int num3 = 8; //rand.nextInt(100);
        int num4 = 16; //rand.nextInt(100);
        int num5 = 32; // rand.nextInt(100);
        int num6 = 64; //rand.nextInt(100);
        int num7 = 128; //rand.nextInt(100);
        int num8 = 256; //rand.nextInt(100);
        int num9 = 512; //rand.nextInt(100);
        int num10 = 1024; // rand.nextInt(100);
       
        Montagem arvore = new Montagem();
        
        arvore.addno(num0, "");
        arvore.addno(num1, "");
        arvore.addno(num2, "");
        arvore.addno(num3, "");
        arvore.addno(num4, "");
        arvore.addno(num5, "");
        arvore.addno(num6, "");
        arvore.addno(num7, "");
        arvore.addno(num8, "");
        arvore.addno(num9, "");
        arvore.addno(num10, "");
        
        
         System.out.println("---------Pos Ordem---------");
          arvore.postOrdem(arvore.raiz);
          System.out.println("**********RAIZ**********: ");
          System.out.println("A raiz é: " + num0);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        
        int num0 =  1; //rand.nextInt(100);
        int num1 = 2; //rand.nextInt(100);
        int num2 = 4; // rand.nextInt(100);
        int num3 = 8; //rand.nextInt(100);
        int num4 = 16; //rand.nextInt(100);
        int num5 = 32; // rand.nextInt(100);
        int num6 = 64; //rand.nextInt(100);
        int num7 = 128; //rand.nextInt(100);
        int num8 = 256; //rand.nextInt(100);
        int num9 = 512; //rand.nextInt(100);
        int num10 = 1024; // rand.nextInt(100);
       
        Montagem arvore = new Montagem();
        
        arvore.addno(num0, "");
        arvore.addno(num1, "");
        arvore.addno(num2, "");
        arvore.addno(num3, "");
        arvore.addno(num4, "");
        arvore.addno(num5, "");
        arvore.addno(num6, "");
        arvore.addno(num7, "");
        arvore.addno(num8, "");
        arvore.addno(num9, "");
        arvore.addno(num10, "");
        
         System.out.println("---------Em Ordem---------");
         arvore.EmOrdem(arvore.raiz);
         System.out.println("**********RAIZ**********: ");
         System.out.println("A raiz é: " + num0);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        int num0 =  1; //rand.nextInt(100);
        int num1 = 2; //rand.nextInt(100);
        int num2 = 4; // rand.nextInt(100);
        int num3 = 8; //rand.nextInt(100);
        int num4 = 16; //rand.nextInt(100);
        int num5 = 32; // rand.nextInt(100);
        int num6 = 64; //rand.nextInt(100);
        int num7 = 128; //rand.nextInt(100);
        int num8 = 256; //rand.nextInt(100);
        int num9 = 512; //rand.nextInt(100);
        int num10 = 1024; // rand.nextInt(100);
       
        
        

         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Montagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Montagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Montagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Montagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Montagem().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}


class No {
    int chave;
    String nome; 
    
    No filhoEsquerda;
    No filhoDireita;
    
    No(int chave, String nome){
        
        this.chave = chave;
        this.nome = nome;
        
    }
    
    public String toString(){
        return nome + "" + chave;
    }
}